### PR TITLE
Throw a real Error from request() to preserve call stack info

### PR DESCRIPTION
**Pull request by ariofrio**

### CODE REVIEW

**Comment by codetheweb** [comment]
👍 thanks, wasn't sure what the best way to go about this was when writing it.

**Comment by codetheweb** [comment]
Published @0.3.2.

**Comment by ariofrio** [comment]
Jumped the gun on this. Needs call to super() at the beginning of the constructor. Pull request incoming.

**Comment by codetheweb** [comment]
Yep, already fixed it. 😉

**Comment by ariofrio** [comment]
Ah, good. Thanks!

**Comment by ariofrio** [comment]
Might want to do super(options.message) instead so the Error message is set.

**Update:** Never mind, I think that's what this.message does. Testing...

**Update 2:** Right, it works well as-is.

**Pull request merged**
